project:
  type: book
  output-dir: docs

book:
  title: "Machine Learning and Statistics: A Common Ground"
  reader-mode: true
  author: "G. Alexi Rodríguez-Arelis"
  date: today
  abstract: "This book aims to set a common ground between Machine Learning and Statistics regarding regression techniques, using `Python` and `R`, under two perspectives: *inference* and *prediction*."
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    search: true
    right:
      - icon: share
      - text: "About the Author"
        href: about.qmd
  page-footer: 
    left: |
      Copyright 2023, G. Alexi Rodríguez-Arelis
  back-to-top-navigation: true
  site-url: https://alexrod61.github.io/ml-stats-common-ground/
  repo-url: https://github.com/alexrod61/ml-stats-common-ground
  repo-branch: main
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]

bibliography: references.bib

format:
  html:
    theme: flatly
    mermaid: 
      theme: neutral
    fontsize: 1.3em
    linestretch: 1.8
    toc: true
    toc-depth: 3
    toc-title: On this page
    number-sections: true
    number-depth: 3
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    html-math-method: mathjax
    linkcolor: rgb(214, 122, 127)
    grid:
      sidebar-width: 300px
      body-width: 1700px
      margin-width: 350px
      gutter-width: 1.5em

editor: visual

