# Preface {.unnumbered}

Throughout my journey as a postdoctoral fellow in the [Master of Data Science (MDS)](https://masterdatascience.ubc.ca/) at the University of British Columbia, I became aware of the fascinating overlap between Machine Learning and Statistics. Many Data Science students usually come across common Machine Learning/Statistics concepts or ideas that might only differ in names. For instance, simple terms such as weights in supervised learning (and their equivalent statistical counterpart as regression coefficients) might be misleading for students starting their Data Science formation. On the other hand, from an instructor's perspective in a Data Science program that subsets its courses in Machine Learning in `Python` and Statistics in `R`, regression courses in `R` also demand the inclusion of `Python`-related packages as alternative tools. In my MDS teaching experience, this is especially critical for students whose career plans lean towards industry where `Python` is more heavily used.

As a Data Science educator, I view this field as a substantial synergy between Machine Learning and Statistics. Nevertheless, I believe there are still many gaps to be addressed between both disciplines. Thus, closing these critical gaps is imperative in a domain with accelerated growth, such as Data Science. The [MDS Stat-ML dictionary](https://ubc-mds.github.io/resources_pages/terminology/) inspired me to write this book. It basically consists of common ground between foundational supervised learning models from Machine Learning and regression models commonly used in Statistics. I strive to explore common modelling approaches as a primary step while highlighting different terminology found in both fields. Furthermore, this discussion is not limited to a simple conceptual exploration. Hence, the second step is hands-on practice via the corresponding `Python` packages for Machine Learning and `R` for Statistics.

## Audience and Scope

This book mainly focuses on regression analysis and its supervised learning counterpart. Thus, it is not introductory Statistics and Machine Learning material. Instead, the following topics are suggested as prerequisites:

- **Mutivariable Differential Calculus and Linear Algebra.** Certain sections of each chapter pertain to modelling estimation. Therefore, topics such as partial derivatives and matrix algebra are a great asset. You can find helpful learning resources on the [MDS webpage](https://ubc-mds.github.io/resources_pages/learning_resources/).
- **Basic `R` programming.** Knowledge of data wrangling and plotting through `R` [{tidyverse}](https://www.tidyverse.org) is recommended for hands-on practice via the examples provided in each one of the chapters of this book. The MDS courses [DSCI 523 (Programming for Data Manipulation)](https://github.com/UBC-MDS/DSCI_523_r-prog) and [DSCI 531 (Data Visualization I)](https://github.com/UBC-MDS/DSCI_531_viz-1) are ideal examples of this prerequisite.
- **Basic `Python` programming.** When necessary, `Python` [{pandas}](https://pypi.org/project/pandas/) library will be used to perform data wrangling. The MDS course [DSCI 511 (Programming for Data Science)](https://github.com/UBC-MDS/DSCI_511_prog-dsci) is an ideal example of this prerequisite.
- **Foundations of probability and basic distributional knowledge.** The reader should be familiar with elemental discrete and continuous distributions since they are a vital component of any given regression or supervised learning model. The MDS course [DSCI 551 (Descriptive Statistics and Probability for Data Science)](https://ubc-mds.github.io/course-descriptions/DSCI_551_eda-dsci/) is an ideal example of this prerequisite.
- **Foundations of frequentist statistical inference.** One of the Data Science paradigms to be covered in this book is statistical inference, i.e., identifying relationships between different variables in a given population or system of interest via a sampled dataset. I only aim to cover a frequentist approach using inferential tools such as parameter estimation, hypothesis testing, and confidence intervals. The MDS course [DSCI 552 (Statistical Inference and Computation I)](https://github.com/UBC-MDS/DSCI_552_stat-inf-1) is an ideal example of this prerequisite.
- **Foundations of supervised learning.** The second Data Science paradigm to be covered pertains to prediction, which is core in Machine Learning. The reader should be familiar with basic terminology, such as training and testing data, overfitting, underfitting, cross-validation, etc. The MDS course [DSCI 571 (Machine Learning I)](https://github.com/UBC-MDS/DSCI_571_sup-learn-1) provides these foundations.
- **Foundations of feature and model selection.** This prerequisite also relates to Machine Learning and its corresponding prediction paradigm. Basic knowledge of prediction accuracy and variable selection tools is recommended. The MDS course [DSCI 573 (Feature and Model Selection)](https://github.com/UBC-MDS/DSCI_573_feat-model-select) is an ideal example of this prerequisite.

## How this Book is Structured
